"""Core module containing exceptions, config, logging, and shared types."""

from cato.core.exceptions import (
    CatoError,
    CommandArgumentError,
    CommandError,
    CommandExecutionError,
    CommandNotFoundError,
    ConfigFileNotFoundError,
    ConfigValidationError,
    ConfigurationError,
    DisplayError,
    EmbeddingError,
    FileAccessError,
    IOError,
    LLMAuthenticationError,
    LLMConnectionError,
    LLMContextLengthError,
    LLMError,
    LLMRateLimitError,
    LLMResponseError,
    NetworkError,
    StorageConnectionError,
    StorageError,
    StorageQueryError,
    VectorStoreConnectionError,
    VectorStoreError,
)

__all__ = [
    "CatoError",
    "ConfigurationError",
    "ConfigFileNotFoundError",
    "ConfigValidationError",
    "LLMError",
    "LLMConnectionError",
    "LLMAuthenticationError",
    "LLMRateLimitError",
    "LLMContextLengthError",
    "LLMResponseError",
    "VectorStoreError",
    "VectorStoreConnectionError",
    "EmbeddingError",
    "StorageError",
    "StorageConnectionError",
    "StorageQueryError",
    "CommandError",
    "CommandNotFoundError",
    "CommandArgumentError",
    "CommandExecutionError",
    "IOError",
    "FileAccessError",
    "NetworkError",
    "DisplayError",
]
